name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build geosite
        id: build
        env:
          NO_SKIP: true
        run: |
          go run -v .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: geosite.db
          path: geosite.db